[package]
name = "tmt"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.13.3", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenvy = "0.15.7" 
zip = { version = "8.6.0", features = ["deflate"] }
quick-xml = "0.39.2"
axum = { version = "0.8.9", features = ["multipart"] }
html-escape = "0.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tempfile = "3"
tower-http = { version = "0.5", features = ["cors"] }
csv = "1.4.0"
unicode-segmentation = "1.11"
regex = "1"
futures = "0.3"
