[package]
name = "tmt"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.13.3", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenvy = "0.15.7" 
zip = { version = "8.6.0", features = ["deflate"] }
quick-xml = "0.39.2"
pdf_oxide = "0.3"
docx-rs = "0.4.20"
